package cdg.clouddataguidance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class C2SPersistentStorageServices implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "S3 Buckets Storage Indicator")
   private java.lang.String s3BucketsInd;
   @org.kie.api.definition.type.Label(value = "C2S EBS Raw Storage Indicator")
   private java.lang.String EBSInd;
   @org.kie.api.definition.type.Label(value = "C2S Relational Database Services Ind")
   private java.lang.String RDSInd;
   @org.kie.api.definition.type.Label(value = "Dynamo DB Indicator")
   private java.lang.String dynamoDBInd;

   public C2SPersistentStorageServices()
   {
   }

   public java.lang.String getS3BucketsInd()
   {
      return this.s3BucketsInd;
   }

   public void setS3BucketsInd(java.lang.String s3BucketsInd)
   {
      this.s3BucketsInd = s3BucketsInd;
   }

   public java.lang.String getEBSInd()
   {
      return this.EBSInd;
   }

   public void setEBSInd(java.lang.String EBSInd)
   {
      this.EBSInd = EBSInd;
   }

   public java.lang.String getRDSInd()
   {
      return this.RDSInd;
   }

   public void setRDSInd(java.lang.String RDSInd)
   {
      this.RDSInd = RDSInd;
   }

   public java.lang.String getDynamoDBInd()
   {
      return this.dynamoDBInd;
   }

   public void setDynamoDBInd(java.lang.String dynamoDBInd)
   {
      this.dynamoDBInd = dynamoDBInd;
   }

   public C2SPersistentStorageServices(java.lang.String s3BucketsInd,
         java.lang.String EBSInd, java.lang.String RDSInd,
         java.lang.String dynamoDBInd)
   {
      this.s3BucketsInd = s3BucketsInd;
      this.EBSInd = EBSInd;
      this.RDSInd = RDSInd;
      this.dynamoDBInd = dynamoDBInd;
   }

}