package cdg.clouddataguidance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class C2SPersistentStorageGuidance implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Storage Cost based on Storage Type Requirement")
   private java.lang.String storageCost;
   @org.kie.api.definition.type.Label("Storage Type")
   private java.lang.String storageType;
   @org.kie.api.definition.type.Label("Archival Guidance - s3, dynamodb, glacier, NARA archival")
   private java.lang.String archivalGuidance;
   @org.kie.api.definition.type.Label("Content ID")
   private java.lang.String contentID;

   public C2SPersistentStorageGuidance()
   {
   }

   public java.lang.String getStorageCost()
   {
      return this.storageCost;
   }

   public void setStorageCost(java.lang.String storageCost)
   {
      this.storageCost = storageCost;
   }

   public java.lang.String getStorageType()
   {
      return this.storageType;
   }

   public void setStorageType(java.lang.String storageType)
   {
      this.storageType = storageType;
   }

   public java.lang.String getArchivalGuidance()
   {
      return this.archivalGuidance;
   }

   public void setArchivalGuidance(java.lang.String archivalGuidance)
   {
      this.archivalGuidance = archivalGuidance;
   }

   public java.lang.String getContentID()
   {
      return this.contentID;
   }

   public void setContentID(java.lang.String contentID)
   {
      this.contentID = contentID;
   }

   public C2SPersistentStorageGuidance(java.lang.String storageCost,
         java.lang.String storageType, java.lang.String archivalGuidance,
         java.lang.String contentID)
   {
      this.storageCost = storageCost;
      this.storageType = storageType;
      this.archivalGuidance = archivalGuidance;
      this.contentID = contentID;
   }

}