package cdg.clouddataguidance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DataInventory implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Content ID")
   private java.lang.String contentID;
   @org.kie.api.definition.type.Label("Data Owner")
   private java.lang.String dataOwner;
   @org.kie.api.definition.type.Label("Data Steward")
   private java.lang.String dataSteward;
   @org.kie.api.definition.type.Label("Retention or Lifecycle Policies - can be seperate object")
   private java.lang.String lifecyclePolicies;
   @org.kie.api.definition.type.Label("ACL Policies")
   private java.lang.String accessControlPolicies;

   @org.kie.api.definition.type.Label("Budget in $s")
   private java.lang.Integer budget;

   @org.kie.api.definition.type.Label("Data Approved for Movement")
   private java.lang.String approvalInd;

   @org.kie.api.definition.type.Label("Reason for Data Movement Denial - Inactive, No Longer needed")
   private java.lang.String reasonForDenial;

   @org.kie.api.definition.type.Label(value = "Exception Process Required?")
   private java.lang.String exceptionInd;

   @org.kie.api.definition.type.Label(value = "Exception Resolved?")
   private java.lang.String exceptionResolvedInd;

   public DataInventory()
   {
   }

   public java.lang.String getContentID()
   {
      return this.contentID;
   }

   public void setContentID(java.lang.String contentID)
   {
      this.contentID = contentID;
   }

   public java.lang.String getDataOwner()
   {
      return this.dataOwner;
   }

   public void setDataOwner(java.lang.String dataOwner)
   {
      this.dataOwner = dataOwner;
   }

   public java.lang.String getDataSteward()
   {
      return this.dataSteward;
   }

   public void setDataSteward(java.lang.String dataSteward)
   {
      this.dataSteward = dataSteward;
   }

   public java.lang.String getLifecyclePolicies()
   {
      return this.lifecyclePolicies;
   }

   public void setLifecyclePolicies(java.lang.String lifecyclePolicies)
   {
      this.lifecyclePolicies = lifecyclePolicies;
   }

   public java.lang.String getAccessControlPolicies()
   {
      return this.accessControlPolicies;
   }

   public void setAccessControlPolicies(java.lang.String accessControlPolicies)
   {
      this.accessControlPolicies = accessControlPolicies;
   }

   public java.lang.Integer getBudget()
   {
      return this.budget;
   }

   public void setBudget(java.lang.Integer budget)
   {
      this.budget = budget;
   }

   public java.lang.String getApprovalInd()
   {
      return this.approvalInd;
   }

   public void setApprovalInd(java.lang.String approvalInd)
   {
      this.approvalInd = approvalInd;
   }

   public java.lang.String getReasonForDenial()
   {
      return this.reasonForDenial;
   }

   public void setReasonForDenial(java.lang.String reasonForDenial)
   {
      this.reasonForDenial = reasonForDenial;
   }

   public java.lang.String getExceptionInd()
   {
      return this.exceptionInd;
   }

   public void setExceptionInd(java.lang.String exceptionInd)
   {
      this.exceptionInd = exceptionInd;
   }

   public java.lang.String getExceptionResolvedInd()
   {
      return this.exceptionResolvedInd;
   }

   public void setExceptionResolvedInd(java.lang.String exceptionResolvedInd)
   {
      this.exceptionResolvedInd = exceptionResolvedInd;
   }

   public DataInventory(java.lang.String contentID, java.lang.String dataOwner,
         java.lang.String dataSteward, java.lang.String lifecyclePolicies,
         java.lang.String accessControlPolicies, java.lang.Integer budget,
         java.lang.String approvalInd, java.lang.String reasonForDenial,
         java.lang.String exceptionInd, java.lang.String exceptionResolvedInd)
   {
      this.contentID = contentID;
      this.dataOwner = dataOwner;
      this.dataSteward = dataSteward;
      this.lifecyclePolicies = lifecyclePolicies;
      this.accessControlPolicies = accessControlPolicies;
      this.budget = budget;
      this.approvalInd = approvalInd;
      this.reasonForDenial = reasonForDenial;
      this.exceptionInd = exceptionInd;
      this.exceptionResolvedInd = exceptionResolvedInd;
   }

}