package cdg.clouddataguidance;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Data Conditioning Requirements")
public class DataConditioning implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Format of Data - structured/unstructured, geo spatial")
   private java.lang.String formatOfData;
   @org.kie.api.definition.type.Label("Content ID")
   private java.lang.String contentID;
   @org.kie.api.definition.type.Label("Deduplication Required or not")
   private java.lang.String dedupInd;
   @org.kie.api.definition.type.Label("Guide ID")
   private java.lang.String guideID;
   @org.kie.api.definition.type.Label("Originating Activity")
   private java.lang.String orginiatingActivity;
   @org.kie.api.definition.type.Label("Enterprise Conditioner")
   private java.lang.String enterpriseConditioner;
   @org.kie.api.definition.type.Label("Data Steward")
   private java.lang.String dataSteward;

   @org.kie.api.definition.type.Label(value = "Data Conditioning Complete?")
   private java.lang.String conditionedInd;

   public DataConditioning()
   {
   }

   public java.lang.String getFormatOfData()
   {
      return this.formatOfData;
   }

   public void setFormatOfData(java.lang.String formatOfData)
   {
      this.formatOfData = formatOfData;
   }

   public java.lang.String getContentID()
   {
      return this.contentID;
   }

   public void setContentID(java.lang.String contentID)
   {
      this.contentID = contentID;
   }

   public java.lang.String getDedupInd()
   {
      return this.dedupInd;
   }

   public void setDedupInd(java.lang.String dedupInd)
   {
      this.dedupInd = dedupInd;
   }

   public java.lang.String getGuideID()
   {
      return this.guideID;
   }

   public void setGuideID(java.lang.String guideID)
   {
      this.guideID = guideID;
   }

   public java.lang.String getOrginiatingActivity()
   {
      return this.orginiatingActivity;
   }

   public void setOrginiatingActivity(java.lang.String orginiatingActivity)
   {
      this.orginiatingActivity = orginiatingActivity;
   }

   public java.lang.String getEnterpriseConditioner()
   {
      return this.enterpriseConditioner;
   }

   public void setEnterpriseConditioner(java.lang.String enterpriseConditioner)
   {
      this.enterpriseConditioner = enterpriseConditioner;
   }

   public java.lang.String getDataSteward()
   {
      return this.dataSteward;
   }

   public void setDataSteward(java.lang.String dataSteward)
   {
      this.dataSteward = dataSteward;
   }

   public java.lang.String getConditionedInd()
   {
      return this.conditionedInd;
   }

   public void setConditionedInd(java.lang.String conditionedInd)
   {
      this.conditionedInd = conditionedInd;
   }

   public DataConditioning(java.lang.String formatOfData,
         java.lang.String contentID, java.lang.String dedupInd,
         java.lang.String guideID, java.lang.String orginiatingActivity,
         java.lang.String enterpriseConditioner, java.lang.String dataSteward,
         java.lang.String conditionedInd)
   {
      this.formatOfData = formatOfData;
      this.contentID = contentID;
      this.dedupInd = dedupInd;
      this.guideID = guideID;
      this.orginiatingActivity = orginiatingActivity;
      this.enterpriseConditioner = enterpriseConditioner;
      this.dataSteward = dataSteward;
      this.conditionedInd = conditionedInd;
   }

}