package cdg.clouddataguidance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ValidationError implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Error Code")
   private java.lang.String errorCode;
   @org.kie.api.definition.type.Label(value = "Error Description")
   private java.lang.String errorDescription;

   public ValidationError()
   {
   }

   public java.lang.String getErrorCode()
   {
      return this.errorCode;
   }

   public void setErrorCode(java.lang.String errorCode)
   {
      this.errorCode = errorCode;
   }

   public java.lang.String getErrorDescription()
   {
      return this.errorDescription;
   }

   public void setErrorDescription(java.lang.String errorDescription)
   {
      this.errorDescription = errorDescription;
   }

   public ValidationError(java.lang.String errorCode,
         java.lang.String errorDescription)
   {
      this.errorCode = errorCode;
      this.errorDescription = errorDescription;
   }

}